name: Deploy

on: push

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ansible-install
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible -y
          
      - name: install collection
        run: ansible-galaxy collection install -U shubhamtatvamasi.magma
        
      - name: ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY}}
