name: Deploy

on: push

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ansible-install
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible -y
          
      - name: install collection
        run: ansible-galaxy collection install -U shubhamtatvamasi.magma
        
      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ls
